### ISSUE TITLE
update tutorial to v4

### ISSUE THREAD

**Issue by sukrosono** [zeroviscosity/d3-js-step-by-step#1]
hi thanks for your article but i can't follow your [pie chart tutorial](https://github.com/zeroviscosity/d3-js-step-by-step/blob/master/step-1-a-basic-pie-chart.html) with `v.4` and also i don't know where i should change the code. I just want to make sure that your noticing about this.

**Comment by zeroviscosity** [comment]
I'm hoping to get an v4 update posted soon.

**Comment by zeroviscosity** [comment]
I've updated the examples in this repo to target v4 and will be updating the site later today.

**Comment by likev** [comment]
The Full Code at the bottom of the [tutorials](http://zeroviscosity.com/d3-js-step-by-step/step-1-a-basic-pie-chart) have **NOT** been updated to target D3 v4.

**Comment by zeroviscosity** [comment]
Ack! Thanks for mentioning that, @likev. I've updated it accordingly.
